apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: apz-task5
data:
  # Message Queue (Kafka)
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  KAFKA_TOPIC: "counter-transactions"
  KAFKA_COMMIT_EVERY_N: "200"
  KAFKA_COMMIT_EVERY_SEC: "2.0"

  # Hazelcast client config (used by logging-service)
  HZ_CLUSTER_NAME: "dev"
  HZ_MEMBERS: "hazelcast-0.hazelcast:5701,hazelcast-1.hazelcast:5701,hazelcast-2.hazelcast:5701"

  # App-level toggles
  LOG_ALL_TX: "1"
