apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: apz-task5
spec:
  selector:
    app: logging-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: apz-task5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging-service
          image: logging-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: SERVICE_NAME
              value: logging-service
            - name: LOGGING_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
